name: Deploy to Hathora

on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Hathora CLI
        run: npm install -g @hathora/cli

      - name: Deploy to Hathora
        run: |
          hathora-cloud deploy \
            --appId app-de924166-b5de-47a6-a0c4-023479a88623 \
            --token ${{ secrets.HATHORA_TOKEN }} \
            --planName tiny \
            --roomsPerProcess 5 \
            --transportType tls \
            --containerPort 8000 \
            --env '[{"name": "HATHORA_TOKEN", "value": "${{ secrets.HATHORA_TOKEN }}"}, {"name": "NODE_ENV", "value": "production"}]'
