name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: >
          cd server && hathora-cloud deploy \
            --appId app-f5736a0b-9fad-43d6-a928-58475b4e9018 \
            --token ${{ secrets.HATHORA_TOKEN }} \
            --planName tiny \
            --roomsPerProcess 5 \
            --transportType tls \
            --containerPort 8000 \
            --env '[{"name": "HATHORA_TOKEN", "value": "${{ secrets.HATHORA_TOKEN }}"}, {"name": "NODE_ENV", "value": "production"}]'
